--WHAT EMPLOYEE BRINGS IN MOST REVENUE,
WHAT IS DIFFERENCE BETWEEN HIGHEST AND LOWEST EARNER
SELECT * FROM SYS.TABLES WHERE NAME LIKE 
'%FINANCE' KEY IS GROUP BY CURRENCYKEY
SELECT
	*
	TABLES
	INNER JOIN
	CURRENCYKEY
	SELECT
	*
	FROM
	table
	WHERE COLUMN >=4 
	--CREATE TABLE
	WHERE
	CURRENCY RATE
	INNER JOIN
	ORDER QUANTITY
	SUM ORDERQUANTITY
	AVG EMPLOYEEKEY


